import '../styles/global.css'
import { Poppins, JetBrains_Mono } from 'next/font/google'
import { Providers } from './(public)/providers'
export const metadata = {
  title: 'Encurta.me',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon2.ico',
  },
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
})
const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
})
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={`${poppins.className} h-full flex m-0 p-0 select-none overflow-hidden`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
